### ISSUE TITLE
Error running sample code from README

### ISSUE THREAD

**Issue by johnd0e** [becheran/vgn#3]
```
Traceback (most recent call last):
  File "D:\repo\vgn\test.py", line 22, in <module>
    asyncio.run(main())
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\repo\vgn\test.py", line 7, in main
    res = await asyncio.gather(
  File "D:\repo\vgn\vgn\functions.py", line 40, in all_stations
    return conv.to_stations((await self._get(query)).get('Haltestellen'))
  File "D:\repo\vgn\vgn\converter.py", line 31, in to_stations
    return list(map(lambda x: Station(x.get('Haltestellenname'),
  File "D:\repo\vgn\vgn\converter.py", line 34, in <lambda>
    list(map(lambda z: _to_transport_type(z), x.get('Produkte').split(',')))
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by becheran** [comment]
I don't find the time to further maintain this project. If anybody out there wants further maintain/develop this code, please let me know.

**Comment by alex-jung** [comment]
> I don't find the time to further maintain this project. If anybody out there wants further maintain/develop this code, please let me know.

Hi,

I can take over maintaince of this project

**Comment by alex-jung** [comment]
> ```
> Traceback (most recent call last):
>   File "D:\repo\vgn\test.py", line 22, in <module>
>     asyncio.run(main())
>   File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "D:\repo\vgn\test.py", line 7, in main
>     res = await asyncio.gather(
>   File "D:\repo\vgn\vgn\functions.py", line 40, in all_stations
>     return conv.to_stations((await self._get(query)).get('Haltestellen'))
>   File "D:\repo\vgn\vgn\converter.py", line 31, in to_stations
>     return list(map(lambda x: Station(x.get('Haltestellenname'),
>   File "D:\repo\vgn\vgn\converter.py", line 34, in <lambda>
>     list(map(lambda z: _to_transport_type(z), x.get('Produkte').split(',')))
> AttributeError: 'NoneType' object has no attribute 'split'
> ```

That happens because VGN Rest API doesn't support possibility to get all stations any more. In the next release of "vgn" package the function "all_stations" will be removed.
